/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_hernandez_zarbo_abad.Ventanas;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLAutores;
import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLPalabrasClave;
import proyecto2_hernandez_zarbo_abad.EDAux.Articulo;
import proyecto2_hernandez_zarbo_abad.EDAux.FuncionesTXT;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaDeDispersion;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaPorPalabrasClave;

/**
 *
 * @author giovanni
 */
public class AgregarResumen extends javax.swing.JFrame {
    FuncionesTXT f ;
    static TablaDeDispersion tabladd;
    static TablaPorPalabrasClave tablapc;
    
    static ArbolAVLAutores avlAutores;
    static ArbolAVLPalabrasClave avlPalabras;
       
    /**
     * Creates new form Agregar
     */
    public AgregarResumen(TablaDeDispersion tabladd, TablaPorPalabrasClave tablapc, ArbolAVLAutores avlAutores, ArbolAVLPalabrasClave avlPalabras) {
        f= new FuncionesTXT();
        this.tabladd = tabladd;
        this.tablapc = tablapc;
        this.avlAutores =avlAutores;
        this.avlPalabras = avlPalabras;
        initComponents();
        this.setVisible(true);
    }

    
    
    public void simularCargaArticulo(String titulo, String[] autores, String resumen, String[] palabrasClaves,
                                            TablaDeDispersion tabladd, TablaPorPalabrasClave tablapc, 
                                            ArbolAVLAutores avlAutores, ArbolAVLPalabrasClave avlPalabras) {
        
        Articulo nuevoArticulo = new Articulo(titulo, autores, resumen, palabrasClaves);
        
        if (tabladd.buscarPorTitulo(titulo) == null) {
            
            tabladd.insertar(nuevoArticulo);
            tablapc.insertar(nuevoArticulo);
            
            for (String autor : autores) {
                avlAutores.insertar(autor.trim(), nuevoArticulo);
            }
            
            for (String palabra : palabrasClaves) {
                avlPalabras.insertar(palabra.trim());
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        analizar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Dale al boton para buscar y agregar el Resumen:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        agregar.setBackground(new java.awt.Color(255, 255, 255));
        agregar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(60, 63, 65));
        agregar.setText("BUSCAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        analizar1.setBackground(new java.awt.Color(255, 255, 255));
        analizar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar1.setForeground(new java.awt.Color(60, 63, 65));
        analizar1.setText("SALIR");
        analizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel2.setText("AGREGAR RESUMEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar1ActionPerformed
        // TODO add your handling code here:
        VentanaInicio menu = new VentanaInicio(tabladd, tablapc, avlAutores, avlPalabras);
        this.dispose();
    }//GEN-LAST:event_analizar1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Texto", "txt");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(filter);
        File ruta = new File(".");
        fileChooser.setCurrentDirectory(ruta);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

String dir = file.getAbsolutePath(); 
this.f.leerTXT(tabladd, tablapc, avlAutores, avlPalabras, dir);
}
    }//GEN-LAST:event_agregarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarResumen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarResumen(tabladd, tablapc, avlAutores, avlPalabras).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton analizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
