/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_hernandez_zarbo_abad.Ventanas;

import javax.swing.JOptionPane;
import proyecto2_hernandez_zarbo_abad.EDAux.AnalizadorResumen;
import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLAutores;
import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLPalabrasClave;
import proyecto2_hernandez_zarbo_abad.EDAux.Articulo;
import proyecto2_hernandez_zarbo_abad.TablasHash.ListaPalabrasClave;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaDeDispersion;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaPorPalabrasClave;

/**
 *
 * @author giovanni
 */
public class EscogerResumenEspecifico extends javax.swing.JFrame {

    static TablaDeDispersion tabladd;
    static TablaPorPalabrasClave tablapc;

    static ArbolAVLAutores avlAutores;
    static ArbolAVLPalabrasClave avlPalabras;

    /**
     * Creates new form BuscarMenu
     */
    public EscogerResumenEspecifico(TablaDeDispersion tabladd, TablaPorPalabrasClave tablapc, ArbolAVLAutores avlAutores, ArbolAVLPalabrasClave avlPalabras) {
        this.tabladd = tabladd;
        this.tablapc = tablapc;
        this.avlAutores = avlAutores;
        this.avlPalabras = avlPalabras;
        initComponents();
        this.setVisible(true);
        String[] listaAutores = avlAutores.listarAutores();
        for (String autor : listaAutores) {
            this.autor.addItem(autor);
        }
        
         String[] listapc = avlPalabras.listarPalabrasClaves();
        for (String pc : listapc) {
            this.palabraC.addItem(pc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        analizar = new javax.swing.JButton();
        analizar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        autor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        analisis = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        titulo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        analizar2 = new javax.swing.JButton();
        analizar3 = new javax.swing.JButton();
        titulo1 = new javax.swing.JComboBox<>();
        analizar4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        palabraC = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel1.setText("Analisis:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        analizar.setBackground(new java.awt.Color(255, 255, 255));
        analizar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar.setForeground(new java.awt.Color(60, 63, 65));
        analizar.setText("BUSCAR");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jPanel1.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        analizar1.setBackground(new java.awt.Color(255, 255, 255));
        analizar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar1.setForeground(new java.awt.Color(60, 63, 65));
        analizar1.setText("SALIR");
        analizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar1ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel2.setText("BUSCAR RESUMEN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        autor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jPanel1.add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 330, 40));

        analisis.setEditable(false);
        analisis.setColumns(20);
        analisis.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        analisis.setRows(5);
        jScrollPane1.setViewportView(analisis);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 530, 380));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel4.setText("Por Autor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 330, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel5.setText("Por Palabra Clave:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel6.setText("Autores:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setText("Ingrese la palabra clave:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setText("Archivos disponibles:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        analizar2.setBackground(new java.awt.Color(255, 255, 255));
        analizar2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar2.setForeground(new java.awt.Color(60, 63, 65));
        analizar2.setText("BUSCAR");
        analizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar2ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        analizar3.setBackground(new java.awt.Color(255, 255, 255));
        analizar3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar3.setForeground(new java.awt.Color(60, 63, 65));
        analizar3.setText("ANALIZAR");
        analizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar3ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        titulo1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 330, 40));

        analizar4.setBackground(new java.awt.Color(255, 255, 255));
        analizar4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar4.setForeground(new java.awt.Color(60, 63, 65));
        analizar4.setText("ANALIZAR");
        analizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar4ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, 40));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setText("Archivos disponibles:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        palabraC.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jPanel1.add(palabraC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void analizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar1ActionPerformed
        // TODO add your handling code here:
        VentanaInicio menu = new VentanaInicio(tabladd, tablapc, avlAutores, avlPalabras);
        this.dispose();
    }//GEN-LAST:event_analizar1ActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
        // TODO add your handling code here:
        this.titulo.removeAllItems();
        ListaPalabrasClave listaArticulos = tablapc.buscarPalabraClave(this.palabraC.getSelectedItem().toString()); 
        
        if (listaArticulos != null) {
            for (Articulo art : listaArticulos.getArticulos()) {
                this.titulo.addItem(art.getTitulo());
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se encontro esa palabra clave");
        }

    }//GEN-LAST:event_analizarActionPerformed

    private void analizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar2ActionPerformed
        // TODO add your handling code here:
        this.titulo1.removeAllItems();

        Articulo[] articulosPorAutor = avlAutores.buscarPorAutor(this.autor.getSelectedItem().toString());

        if (articulosPorAutor.length > 0) {
            for (Articulo art : articulosPorAutor) {
                this.titulo1.addItem(art.getTitulo());
            }
        } else {
            System.out.println("No se encontraron artículos.");
        }
    }//GEN-LAST:event_analizar2ActionPerformed

    private void analizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar3ActionPerformed
        // TODO add your handling code here:
         Articulo artAnalisis = tabladd.buscarPorTitulo(this.titulo1.getSelectedItem().toString()); 

        if (artAnalisis != null) {
            String[] palabrasClavesGlobales = avlPalabras.listarPalabrasClaves();
            AnalizadorResumen analizador = new AnalizadorResumen();

            this.analisis.setText(analizador.analizar(artAnalisis, palabrasClavesGlobales));
        }
    }//GEN-LAST:event_analizar3ActionPerformed

    private void analizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar4ActionPerformed
        // TODO add your handling code here:
         Articulo artAnalisis = tabladd.buscarPorTitulo(this.titulo.getSelectedItem().toString()); 
        if (artAnalisis != null) {
            String[] palabrasClavesGlobales = avlPalabras.listarPalabrasClaves();
            AnalizadorResumen analizador = new AnalizadorResumen();

            this.analisis.setText(analizador.analizar(artAnalisis, palabrasClavesGlobales));
        }
    }//GEN-LAST:event_analizar4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscogerResumenEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscogerResumenEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscogerResumenEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscogerResumenEspecifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscogerResumenEspecifico(tabladd, tablapc, avlAutores, avlPalabras).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea analisis;
    private javax.swing.JButton analizar;
    private javax.swing.JButton analizar1;
    private javax.swing.JButton analizar2;
    private javax.swing.JButton analizar3;
    private javax.swing.JButton analizar4;
    private javax.swing.JComboBox<String> autor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> palabraC;
    private javax.swing.JComboBox<String> titulo;
    private javax.swing.JComboBox<String> titulo1;
    // End of variables declaration//GEN-END:variables
}
