/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_hernandez_zarbo_abad.Ventanas;

import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLAutores;
import proyecto2_hernandez_zarbo_abad.ArbolesAVL.ArbolAVLPalabrasClave;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaDeDispersion;
import proyecto2_hernandez_zarbo_abad.TablasHash.TablaPorPalabrasClave;
import proyecto2_hernandez_zarbo_abad.Ventanas.EscogerResumenEspecifico;
import proyecto2_hernandez_zarbo_abad.Ventanas.AnalizarResumenGeneral;
import proyecto2_hernandez_zarbo_abad.Ventanas.AgregarResumen;

/**
 *
 * @author giovanni
 */
public class VentanaInicio extends javax.swing.JFrame {
    static TablaDeDispersion tabladd;
    static TablaPorPalabrasClave tablapc;
    
    static ArbolAVLAutores avlAutores;
    static ArbolAVLPalabrasClave avlPalabras;
    /**
     * Creates new form Menu
     */
    public VentanaInicio(TablaDeDispersion tabladd, TablaPorPalabrasClave tablapc, ArbolAVLAutores avlAutores, ArbolAVLPalabrasClave avlPalabras) {
        this.tabladd = tabladd;
        this.tablapc = tablapc;
        this.avlAutores =avlAutores;
        this.avlPalabras = avlPalabras;
        initComponents();
        this.setVisible(true);
        System.out.println("========================MENU============================");
        for (int i = 0; i < tabladd.total; i++) {
            try{
                System.out.println(tabladd.articulos[i].getTitulo());
            }catch(Exception e){
                
            }
        }
        System.out.println("******************************************************");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        analizar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        analizar1 = new javax.swing.JButton();
        analizar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        analizar.setBackground(new java.awt.Color(255, 255, 255));
        analizar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar.setForeground(new java.awt.Color(60, 63, 65));
        analizar.setText("ANALIZAR RESUMEN");
        analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarActionPerformed(evt);
            }
        });
        jPanel1.add(analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        agregar.setBackground(new java.awt.Color(255, 255, 255));
        agregar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(60, 63, 65));
        agregar.setText("AGREGAR RESUMEN");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        analizar1.setBackground(new java.awt.Color(255, 255, 255));
        analizar1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar1.setForeground(new java.awt.Color(60, 63, 65));
        analizar1.setText("SALIR");
        jPanel1.add(analizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        analizar2.setBackground(new java.awt.Color(255, 255, 255));
        analizar2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        analizar2.setForeground(new java.awt.Color(60, 63, 65));
        analizar2.setText("BUSCAR RESUMEN");
        analizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizar2ActionPerformed(evt);
            }
        });
        jPanel1.add(analizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        AgregarResumen agregar = new AgregarResumen(tabladd, tablapc, avlAutores, avlPalabras);

        this.dispose();
    }//GEN-LAST:event_agregarActionPerformed

    private void analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarActionPerformed
        // TODO add your handling code here:
        AnalizarResumenGeneral analizar = new AnalizarResumenGeneral(tabladd, tablapc, avlAutores, avlPalabras);
        this.dispose();
    }//GEN-LAST:event_analizarActionPerformed

    private void analizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizar2ActionPerformed
        // TODO add your handling code here:
        EscogerResumenEspecifico buscar = new EscogerResumenEspecifico(tabladd, tablapc, avlAutores, avlPalabras);
        this.dispose();
    }//GEN-LAST:event_analizar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio(tabladd, tablapc, avlAutores, avlPalabras).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton analizar;
    private javax.swing.JButton analizar1;
    private javax.swing.JButton analizar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
